name: Publish package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"
          registry-url: "https://npm.pkg.github.com"
          scope: "@greenpass-venture"
      - run: npm version 1.0.${{ github.run_id }}${{github.run_attempt}} --no-git-tag-version
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
